import Test.KeyValueStoreExample.KeyValueStore
import Plausible.Arbitrary
import Plausible.DeriveArbitrary
import Plausible.Chamelean.ArbitrarySizedSuchThat
import Plausible.Chamelean.DeriveChecker
import Plausible.Chamelean.DeriveConstrainedProducer
import Plausible.Chamelean.EnumeratorCombinators
import Plausible.Chamelean.GeneratorCombinators

open Plausible
open KeyValueStore

-- Suppress warnings for unused variables in derived generators/checkers
set_option linter.unusedVariables false

-- Suppress warnings for redundant pattern-match cases in derived generators/checkers
set_option match.ignoreUnusedAlts true

/-- We override the default `Arbitrary` for `String`s so that we only produce strings of length 1
    where the string is a single letter from `A` to `I` -/
instance instKeyValueStoreArbitraryString : Arbitrary String where
  arbitrary := GeneratorCombinators.elementsWithDefault "A" ["A", "B", "C", "D", "E", "F", "G", "H", "I"]

---------------------------------------------------------------------------------------------------------------------------------------
-- Derived Checkers & Generators (everything below in this file is automatically generated by Chamelean)
---------------------------------------------------------------------------------------------------------------------------------------

#guard_msgs(drop info, drop warning) in
#derive_generator (fun (s1 : List (String × String)) => KeyValueStore.RemoveKV k s1 s2)

#guard_msgs(drop info, drop warning) in
#derive_generator (fun (s2 : List (String × String)) => KeyValueStore.RemoveKV k s1 s2)


#guard_msgs(drop info, drop warning) in
#derive_generator (fun (s1 : List (String × String)) => KeyValueStore.AddKV k v s1 s2)

#guard_msgs(drop info, drop warning) in
#derive_generator (fun (s2 : List (String × String)) => KeyValueStore.AddKV k v s1 s2)

#guard_msgs(drop info, drop warning) in
#derive_generator (fun (v : String) => KeyValueStore.AddKV k v x_1 s2)

#guard_msgs(drop info, drop warning) in
#derive_checker (KeyValueStore.LookupKV s kv)

#guard_msgs(drop info, drop warning) in
#derive_generator (fun (s1 : List (String × String)) => KeyValueStore.LookupKV s1 kv)

#guard_msgs(drop info, drop warning) in
#derive_checker (KeyValueStore.AddKV k2 v s_1 s2)

#guard_msgs(drop info, drop warning) in
#derive_generator (fun (s : List (String × String)) => KeyValueStore.EvalStateApiCall s x)

#guard_msgs(drop info, drop warning) in
#derive_generator (fun (kv : StateResult × String × Nat × String) => KeyValueStore.LookupKV s kv)

#guard_msgs(drop info, drop warning) in
#derive_generator (fun (nb : Nat × List (String × String)) => KeyValueStore.GetBucket s nb)

#guard_msgs(drop info, drop warning) in
#derive_generator (fun (foo : StateAPICall × StateResult × List (String × String)) => KeyValueStore.EvalStateApiCall x foo)

#guard_msgs(drop info, drop warning) in
#derive_generator (fun (crns : APICall × Result × (Nat × List (Nat × List (String × String)))) => KeyValueStore.EvalApiCall s crns)

#guard_msgs(drop info, drop warning) in
#derive_generator (fun (o : List (APICall × Result) × (Nat × List (Nat × List (String × String)))) => KeyValueStore.EvalApiCalls s o)


/- Uncommenting the following line results in random sequences of API Calls, such as:

```lean
 ([(APICall.CreateBucket, Result.Created 0),
  (APICall.OpBucket 0 (StateAPICall.Delete "B"),
   Result.OpResult (StateResult.NoSuchKeyFailure)),
  (APICall.CreateBucket, Result.Created 1),
  (APICall.DeleteBucket 0, Result.Removed),
  (APICall.CreateBucket, Result.Created 2),
  (APICall.CreateBucket, Result.Created 3),
  (APICall.DeleteBucket 1, Result.Removed),
  (APICall.CreateBucket, Result.Created 4),
  (APICall.DeleteBucket 2, Result.Removed),
  (APICall.OpBucket 3 (StateAPICall.Get "E" none),
   Result.OpResult (StateResult.NoSuchKeyFailure)),
  (APICall.CreateBucket, Result.Created 5),
  (APICall.OpBucket 3 (StateAPICall.Append "B" "D"),
   Result.OpResult (StateResult.NoSuchKeyFailure)),
  (APICall.DeleteBucket 3, Result.Removed),
  (APICall.CreateBucket, Result.Created 6)],
 7,
 [(6, []), (5, []), (4, [])])
```

-/
-- #eval Gen.run (ArbitrarySizedSuchThat.arbitrarySizedST (fun crs => KeyValueStore.EvalApiCalls (0, []) crs) 20) 20
